name: Scrap US stock data and calculate RS rating all.

on:
  schedule:
    - cron: "10 22 * * 1-5"
  workflow_dispatch: {}
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Grant execute permission to S&P500 script
      run: chmod +x ./calc-sp500-rs.py
    - name: Grant execute permission to NASDAQ script
      run: chmod +x ./calc-nasdaq-rs.py
    - name: Run S&P500 script
      run: |
        ./calc-sp500-rs.py
    - name: Run NASDAQ script
      run: |
        ./calc-nasdaq-rs.py
    - name: Commits
      run: |
        git config --local user.email "remaster5@gmail.com"
        git config --local user.name "remaster5"
        git add .
        git commit -m "[AUTO] Daily US RS rating"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'
        github_token: ${{ secrets.GITHUB_TOKEN }}
